name: continental_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

  equatable: ^2.0.5
  uuid: ^4.4.2
  
  http: ^1.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  camera: ^0.11.0+1
  flutter_image_compress: ^2.3.0

  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  # flutter_address_from_latlng: ^0.0.2
  
  shared_preferences: ^2.2.3
  flutter_keychain: ^2.5.0
  tuple: ^2.0.2
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  bloc_test: ^9.1.7
  test: ^1.24.9

  build_runner: ^2.4.9
  sqflite_common_ffi: ^2.1.1+1

  flutter_keychain: ^2.5.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
